spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/playground
    username: playground
    password: playground
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 30m

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
